### ISSUE TITLE
White spaces were not rendered

### ISSUE THREAD

**Issue by DiepEsc** [archriss/react-native-render-html#216]
### First words
I think the cause is on this line: [HTML.js#L269](https://github.com/archriss/react-native-render-html/blob/40293bad8013a3a91f86c04da07f80f94fe15be6/src/HTML.js#L269)
(The regex pattern `/\s/g `)
### Is this a bug report or a feature request?

Bug report.

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

No.

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes.

### Have you made sure that your issue hasn't already been reported/solved?

I have searched. It could be alternative to [#118](https://github.com/archriss/react-native-render-html/issues/118)

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Tested on Android.

### Is the bug reproductible in a production environment (not a debug one)?

Not tested yet.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Not tested yet.

### Environment

Environment:
    React: 16.6.0-alpha.8af6728
    React native: 0.57.4
    react-native-render-html: 3.10.0

  Target Platform:
    Android (7.0)

### Steps to Reproduce

1. Render html with a tag contain white spaces **only** (unicode white space)

### Expected Behavior
white spaces should be rendered. They are not breaking spaces.

(Write what you thought would happen.) 
### Actual Behavior

White spaces were not rendered.

### Reproducible Demo

Not implement yet.

**Comment by jr-k** [comment]
Same problem

**Comment by alexisbronchart** [comment]
I'm having the same issue. It happens in iOS as well. I'll post a repro soon.

**Comment by grnkvch** [comment]
> Same problem, only spaces between 2 html tags like
> 
> ```js
> render() {
>     const html = '<strong><em>Hello</em><strong> <strong>World</strong>';
>     return (<HTML html={html}/>);
> }
> ```
> 
> Result:
> ![HelloWorld](https://camo.githubusercontent.com/4785a2edd0629d17455b953810e5d226626d4a2b/68747470733a2f2f692e6962622e636f2f573054477868532f68656c6c6f776f726c642e706e67)
> 
> Shitty fix:
> 
> ```js
> const html = '<strong><em>Hello</em><strong> <strong>World</strong>';
> const fixedHtml = html.replace(/> </g, '><span style="color:white;">-</span><');
> ```

.replace(/\/a>\s<a/g, '/a>­ <a') works as well

**Comment by alexisbronchart** [comment]
This line https://github.com/archriss/react-native-render-html/blob/928d8e825377181f383934f0b33747ae1315f345/src/HTML.js#L272 could be replaced with:
`const strippedData = data && data.replace(/\s+/g, ' ')`

**Comment by DiepEsc** [comment]
The regex pattern should be /[\t\r\n ]+/g instead of \s. Because \s is included many types of unicode spaces. There types of space should be rendered in HTML.

Wikipedia page about white spaces:
https://en.m.wikipedia.org/wiki/Whitespace_character

**Comment by caioiglesias** [comment]
Isn't this issue fixed with https://github.com/thoughtis/react-native-render-html/pull/1 ?

**Comment by jsamr** [comment]
@caioiglesias It has not been merged on master of *this* repository. The pending PR is #350. We are looking into it.

**Comment by jsamr** [comment]
@DiepEsc That is already handled [L277](https://github.com/archriss/react-native-render-html/blob/47b159d4e42de37328609f2bf93f53e299cdc958/src/HTML.js#L277)

**Comment by jsamr** [comment]
I'm closing this issue in favor of #118. The solution to this issue is complex, and won't be included before release 6.0.

**Comment by trungphamduc0401** [comment]
@jsamr I am still encountering this bug in 6.3.1. Please help check. Many thanks
